import { sql } from 'drizzle-orm';
import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const serverSeeds = sqliteTable('server_seeds', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  seed: text('seed').notNull(),
  seedHash: text('seed_hash').notNull(),
  isActive: integer('is_active', { mode: 'boolean' }).default(true),
  totalBets: integer('total_bets', { mode: 'number' }).default(0),
  revealedAt: integer('revealed_at', { mode: 'timestamp' }),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`),
});

export const wallets = sqliteTable('wallets', {
  walletId: text('wallet_id').primaryKey(),
  discordId: text('discord_id').notNull().unique(),
  username: text('username').notNull().unique(),
  usernameLower: text('username_lower').notNull().unique(),
  avatarHash: text('avatar_hash'),
  shards: integer('shards', { mode: 'number' }).default(500),
  gems: integer('gems', { mode: 'number' }).default(0),
  rep: integer('rep', { mode: 'number' }).default(0),
  seedEncrypted: text('seed_encrypted').notNull(),
  seedIv: text('seed_iv').notNull(),
  seedTag: text('seed_tag').notNull(),
  twoFactorSecret: text('two_factor_secret'),
  termsAccepted: integer('terms_accepted', { mode: 'boolean' }).default(false),
  termsAcceptedAt: integer('terms_accepted_at', { mode: 'timestamp' }),
  onboardingStep: integer('onboarding_step', { mode: 'number' }).default(0),
  isVerified: integer('is_verified', { mode: 'boolean' }).default(false),
  isBanned: integer('is_banned', { mode: 'boolean' }).default(false),
  banReason: text('ban_reason'),
  riskScore: integer('risk_score', { mode: 'number' }).default(0),
  totalWagered: integer('total_wagered', { mode: 'number' }).default(0),
  totalWon: integer('total_won', { mode: 'number' }).default(0),
  totalLost: integer('total_lost', { mode: 'number' }).default(0),
  dailyStreak: integer('daily_streak', { mode: 'number' }).default(0),
  lastDaily: integer('last_daily', { mode: 'timestamp' }),
  lastActive: integer('last_active', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`),
  gamesPlayed: integer('games_played', { mode: 'number' }).default(0),
  clientSeed: text('client_seed'),
  serverSeedId: integer('server_seed_id').references(() => serverSeeds.id),
  nonce: integer('nonce', { mode: 'number' }).default(0),
  accountCreatedAt: integer('account_created_at', { mode: 'timestamp' }),
  joinedServerAt: integer('joined_server_at', { mode: 'timestamp' }),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`),
});

export const transactions = sqliteTable('transactions', {
  txId: text('tx_id').primaryKey(),
  walletId: text('wallet_id').notNull().references(() => wallets.walletId),
  type: text('type').notNull(),
  currency: text('currency').default('shards'),
  amount: integer('amount', { mode: 'number' }).notNull(),
  balanceBefore: integer('balance_before', { mode: 'number' }).notNull(),
  balanceAfter: integer('balance_after', { mode: 'number' }).notNull(),
  referenceId: text('reference_id'),
  referenceType: text('reference_type'),
  counterpartyId: text('counterparty_id').references(() => wallets.walletId),
  description: text('description'),
  channelId: text('channel_id'),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`),
  txHash: text('tx_hash').notNull(),
});

export const bets = sqliteTable('bets', {
  betId: text('bet_id').primaryKey(),
  walletId: text('wallet_id').notNull().references(() => wallets.walletId),
  game: text('game').notNull(),
  amount: integer('amount', { mode: 'number' }).notNull(),
  multiplier: real('multiplier'),
  payout: integer('payout', { mode: 'number' }).notNull(),
  profit: integer('profit', { mode: 'number' }).notNull(),
  serverSeedHash: text('server_seed_hash').notNull(),
  serverSeed: text('server_seed'),
  clientSeed: text('client_seed').notNull(),
  nonce: integer('nonce', { mode: 'number' }).notNull(),
  resultHex: text('result_hex').notNull(),
  resultFloat: real('result_float').notNull(),
  resultDisplay: text('result_display').notNull(),
  status: text('status').default('resolved'),
  verifiedByUser: integer('verified_by_user', { mode: 'boolean' }).default(false),
  channelId: text('channel_id'),
  opponentId: text('opponent_id').references(() => wallets.walletId),
  createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`),
});

export const withdrawals = sqliteTable('withdrawals', {
  id: text('id').primaryKey(),
  walletId: text('wallet_id').notNull().references(() => wallets.walletId),
  amount: integer('amount', { mode: 'number' }).notNull(),
  currency: text('currency').default('shards'),
  status: text('status').default('pending'),
  requestedAt: integer('requested_at', { mode: 'timestamp' }).default(sql`CURRENT_TIMESTAMP`),
  cooldownUntil: integer('cooldown_until', { mode: 'timestamp' }),
  processedAt: integer('processed_at', { mode: 'timestamp' }),
  riskFlags: text('risk_flags'),
  adminReviewed: integer('admin_reviewed', { mode: 'boolean' }).default(false),
  txId: text('tx_id').references(() => transactions.txId),
});

export const dailyLimits = sqliteTable('daily_limits', {
  walletId: text('wallet_id').primaryKey().references(() => wallets.walletId),
  date: text('date').default(sql`CURRENT_DATE`),
  withdrawalsToday: integer('withdrawals_today', { mode: 'number' }).default(0),
  amountWithdrawn: integer('amount_withdrawn', { mode: 'number' }).default(0),
  maxWithdrawals: integer('max_withdrawals', { mode: 'number' }).default(1),
  maxAmount: integer('max_amount', { mode: 'number' }).default(10000),
  lastWithdrawal: integer('last_withdrawal', { mode: 'timestamp' }),
  nextAllowed: integer('next_allowed', { mode: 'timestamp' }),
});
